ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email         VARCHAR(255) UNIQUE,
    ADD COLUMN IF NOT EXISTS password_hash TEXT,
    ADD COLUMN IF NOT EXISTS plan          VARCHAR(20) NOT NULL DEFAULT 'free';

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
